events {}

http {
  upstream pos_service {
    server pos-service:4001;
  }

  upstream hr_service {
    server hr-service:4002;
  }

  server {
    listen 80;

    location /pos/ {
      proxy_pass http://pos_service/;
    }

    location /hr/ {
      proxy_pass http://hr_service/;
    }

    location /inventory/ {
      proxy_pass http://inventory-service:4003/;
    }

    location /procurement/ {
      proxy_pass http://procurement-service:4004/;
    }

    location /admin/ {
      proxy_pass http://admin-service:4005/;
    }

    location /analytics/ {
      proxy_pass http://analytics-service:4006/;
    }
  }
}