global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'services'
    static_configs:
      - targets:
          - pos-service:4001
          - hr-service:4002
          - inventory-service:4003
          - procurement-service:4004
          - admin-service:4005
          - analytics-service:4006